# Generated by Django 3.0.1 on 2020-03-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userencoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='userencoding',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
