# Generated by Django 3.1.2 on 2020-10-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("face_detection", "0002_auto_20191227_1835"),
        ("app", "0003_userencoding_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="userencoding",
            name="matches",
            field=models.ManyToManyField(
                related_name="matches", to="face_detection.FaceEncoding"
            ),
        ),
    ]
