import numpy as np
from django.db.models import Model, FloatField, IntegerField, TextField


class FaceEncoding(Model):
    user_id = IntegerField(blank=True, null=True)
    album_id = IntegerField(blank=True, null=True)
    image_id = IntegerField(blank=True, null=True)

    field0 = FloatField()
    field1 = FloatField()
    field2 = FloatField()
    field3 = FloatField()
    field4 = FloatField()
    field5 = FloatField()
    field6 = FloatField()
    field7 = FloatField()
    field8 = FloatField()
    field9 = FloatField()
    field10 = FloatField()
    field11 = FloatField()
    field12 = FloatField()
    field13 = FloatField()
    field14 = FloatField()
    field15 = FloatField()
    field16 = FloatField()
    field17 = FloatField()
    field18 = FloatField()
    field19 = FloatField()
    field20 = FloatField()
    field21 = FloatField()
    field22 = FloatField()
    field23 = FloatField()
    field24 = FloatField()
    field25 = FloatField()
    field26 = FloatField()
    field27 = FloatField()
    field28 = FloatField()
    field29 = FloatField()
    field30 = FloatField()
    field31 = FloatField()
    field32 = FloatField()
    field33 = FloatField()
    field34 = FloatField()
    field35 = FloatField()
    field36 = FloatField()
    field37 = FloatField()
    field38 = FloatField()
    field39 = FloatField()
    field40 = FloatField()
    field41 = FloatField()
    field42 = FloatField()
    field43 = FloatField()
    field44 = FloatField()
    field45 = FloatField()
    field46 = FloatField()
    field47 = FloatField()
    field48 = FloatField()
    field49 = FloatField()
    field50 = FloatField()
    field51 = FloatField()
    field52 = FloatField()
    field53 = FloatField()
    field54 = FloatField()
    field55 = FloatField()
    field56 = FloatField()
    field57 = FloatField()
    field58 = FloatField()
    field59 = FloatField()
    field60 = FloatField()
    field61 = FloatField()
    field62 = FloatField()
    field63 = FloatField()
    field64 = FloatField()
    field65 = FloatField()
    field66 = FloatField()
    field67 = FloatField()
    field68 = FloatField()
    field69 = FloatField()
    field70 = FloatField()
    field71 = FloatField()
    field72 = FloatField()
    field73 = FloatField()
    field74 = FloatField()
    field75 = FloatField()
    field76 = FloatField()
    field77 = FloatField()
    field78 = FloatField()
    field79 = FloatField()
    field80 = FloatField()
    field81 = FloatField()
    field82 = FloatField()
    field83 = FloatField()
    field84 = FloatField()
    field85 = FloatField()
    field86 = FloatField()
    field87 = FloatField()
    field88 = FloatField()
    field89 = FloatField()
    field90 = FloatField()
    field91 = FloatField()
    field92 = FloatField()
    field93 = FloatField()
    field94 = FloatField()
    field95 = FloatField()
    field96 = FloatField()
    field97 = FloatField()
    field98 = FloatField()
    field99 = FloatField()
    field100 = FloatField()
    field101 = FloatField()
    field102 = FloatField()
    field103 = FloatField()
    field104 = FloatField()
    field105 = FloatField()
    field106 = FloatField()
    field107 = FloatField()
    field108 = FloatField()
    field109 = FloatField()
    field110 = FloatField()
    field111 = FloatField()
    field112 = FloatField()
    field113 = FloatField()
    field114 = FloatField()
    field115 = FloatField()
    field116 = FloatField()
    field117 = FloatField()
    field118 = FloatField()
    field119 = FloatField()
    field120 = FloatField()
    field121 = FloatField()
    field122 = FloatField()
    field123 = FloatField()
    field124 = FloatField()
    field125 = FloatField()
    field126 = FloatField()
    field127 = FloatField()

    @staticmethod
    def encoding_to_model(image_id, album_id, encoding_array):
        encoding = FaceEncoding(image_id=image_id, album_id=album_id)
        for i in range(0, 128):
            setattr(encoding, f'field{i}', encoding_array[i])
        return encoding

    def fields_to_encoding(self):
        return np.array([getattr(self, f'field{i}') for i in range(0,  128)])

